Settings Page
pastelnata/Swipe4Paws pull request #106
Opened 2024-12-16 21:45 UTC by Dobos23

Added a functional Settings Page enabling users to change usernames and passwords.

2024-12-16 22:00 UTC, pastelnata requested changes

2024-12-16 22:00 UTC, pastelnata commented on backend/src/controllers/UserController.ts
> +      res.status(200).json({success});
dont forget to generate a new token after updating the user

2024-12-17 13:08 UTC, alikrist commented
branch has conflicts in front-end routes

2024-12-17 15:18 UTC, Dobos23 commented
conflicts solved, the rest is handled by Hubert

2024-12-17 15:23 UTC, pastelnata commented
![image](https://github.com/user-attachments/assets/81a95b40-7ac9-43ec-bfed-dff0b0aeade0)

2024-12-17 15:31 UTC, pastelnata commented
I solved but but now i cannot merge cause i pushed changes lol

2024-12-17 15:41 UTC, sduhubert approved these changes
slauy

2024-12-17 15:43 UTC, merged